version: '3.8'

services:
  mars_db:
    image: postgres:15-alpine
    container_name: mars_postgres_container
    environment:
      POSTGRES_USER: zazaki
      POSTGRES_PASSWORD: hackathon2026
      POSTGRES_DB: mars_habitat
    ports:
      - "5432:5432"
    networks:
      - mars_network
    volumes:
      - mars_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mars_network:
    external: true

volumes:
  mars_db_data:
